server:
  port: 3000

db:
  type: 'postgres'
  port: 5432
  db_name: 'tma_database'

mongodb:
  url: 'mongodb+srv://djanju410:h5dHe90B07dnrYu8@cluster0.4ralh.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0'

jwt:
  expiresIn: 3600
